### ISSUE TITLE
设置 Bili 订阅时的报错

### ISSUE THREAD

**Issue by AnotiaWang** [StarWishsama/Nameless-Bot#111]
## 描述 (必须)

在一个700人的群里设置Bili订阅动态，机器人没有反应，unsub的时候提示没有订阅，但是在我的测试群里可以正常推送动态信息。

其他信息：
- 我和bot都是普通群员
- 已经在config.yml中设置了B站帐号密码，但是重启bot之后内容被覆盖（消失）了
- 在groups文件夹下对应群的配置里发现bili_sub为空

## 复现步骤 (必须)

发送`/bili sub xxxx`，机器人回复已订阅成功
发送`/bili unsub xxxx`，机器人提示还没有订阅该up

这是出问题的群：
![Screenshot_20201109-120414226.jpg](https://user-images.githubusercontent.com/62269186/98499249-ee5c0400-2283-11eb-8297-d98f68a268c8.jpg)

正常的群：
![Screenshot_20201109-121610548.jpg](https://user-images.githubusercontent.com/62269186/98499781-91614d80-2285-11eb-8d25-3912f6779fe2.jpg)

## Log / Comet-Bot 的报错

发现了两种报错
```
cn.hutool.core.io.IORuntimeException: IOException: File length is [220869] but read [-1]!
	at cn.hutool.core.io.file.FileReader.readBytes(FileReader.java:129)
	at cn.hutool.core.io.file.FileReader.readString(FileReader.java:144)
	at io.github.starwishsama.comet.utils.FileUtilKt.getContext(FileUtil.kt:35)
	at io.github.starwishsama.comet.Comet$startBot$2$1.invoke(Comet.kt:119)
	at io.github.starwishsama.comet.Comet$startBot$2$1.invoke(Comet.kt:45)
	at net.mamoe.mirai.utils.PlatformLogger.printLog(PlatformLogger.jvm.kt:62)
	at net.mamoe.mirai.utils.PlatformLogger.info0(PlatformLogger.jvm.kt:86)
	at net.mamoe.mirai.utils.MiraiLoggerPlatformBase.info(MiraiLogger.kt:383)
	at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:144)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: File length is [220869] but read [-1]!
	at cn.hutool.core.io.file.FileReader.readBytes(FileReader.java:126)
	... 17 more
```

```
W/CometService: 在获取动态时出现了异常
java.lang.NullPointerException: dynamicObject.asJsonObje…a"].asJsonObject["cards"] must not be null
	at io.github.starwishsama.comet.api.thirdparty.bilibili.MainApi.getDynamic(MainApi.kt:50)
	at io.github.starwishsama.comet.pushers.BiliDynamicChecker$retrieve$2$data$1.invokeSuspend(BiliDynamicChecker.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.starwishsama.comet.pushers.BiliDynamicChecker$retrieve$2.accept(BiliDynamicChecker.kt:34)
	at io.github.starwishsama.comet.pushers.BiliDynamicChecker$retrieve$2.accept(BiliDynamicChecker.kt:15)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at io.github.starwishsama.comet.pushers.BiliDynamicChecker.retrieve(BiliDynamicChecker.kt:33)
	at io.github.starwishsama.comet.Comet$startAllPusher$$inlined$forEach$lambda$1.invoke(Comet.kt:108)
	at io.github.starwishsama.comet.Comet$startAllPusher$$inlined$forEach$lambda$1.invoke(Comet.kt:45)
	at io.github.starwishsama.comet.utils.TaskUtil$sam$java_lang_Runnable$0.run(TaskUtil.kt)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## 使用环境 (必须)

Ubuntu 20 LTS
1核 2G

 - Java 版本:
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-0ubuntu1~20.04-b10)OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
```
 - Comet-Bot 版本: 0.6-M2

**Comment by StarWishsama** [comment]
你好 退订的时候只能用 UID 的

**Comment by AnotiaWang** [comment]
> 你好 退订的时候只能用 UID 的

好的，那只要bot回复订阅成功就是代表成功了吗？为啥我在群的配置文件里没有看到，那里面记录的好像和机器人报的不一样

```
Bot >  订阅 原神(401742377) 成功
```
```
  "bili_sub": [
    269310,
    21987615
  ],
```

**Comment by StarWishsama** [comment]
> > 你好 退订的时候只能用 UID 的
> 
> 好的，那只要bot回复订阅成功就是真的成功了吗？为啥我在群的配置文件里没有看到

群配置文件不是实时写入的，都是关闭后才保存到文件

**Comment by AnotiaWang** [comment]
这样啊，懂了

那，重启bot之后，config.yml 修改的内容消失是为啥，

**Comment by StarWishsama** [comment]
> 这样啊，懂了
> 
> 那，重启bot之后，config.yml 修改的内容消失是为啥，

逻辑问题，现在是 Bot 关闭后把已经加载的配置再直接覆盖原有文件。
你可以在修改完之后使用 /debug reload 重载配置文件，或者等待下个版本添加的后台命令 /admin reload。

**Comment by AnotiaWang** [comment]
好的，谢谢~
