### ISSUE TITLE
.bili info 与.bili sub 使用时提示 在试图执行命令时发生了一个错误, 请联系管理员

### ISSUE THREAD

**Issue by Damonlove** [StarWishsama/Nameless-Bot#233]
## 描述 (必须)
使用.bili sub 用户名 时报错
使用.bili info 用户名 时报错
## 复现步骤 (必须)
![image](https://user-images.githubusercontent.com/44105629/119604286-630e1e80-be21-11eb-918f-066f75e2b404.png)
![image](https://user-images.githubusercontent.com/44105629/119604396-918bf980-be21-11eb-8b0a-5e6b3b3d2a85.png)

## Log / Comet-Bot 的报错
java.io.IOException: canceled due to java.lang.NullPointerException
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NullPointerException
                at com.hiczp.bilibili.api.passport.model.LoginResponse.getToken(LoginResponse.kt:60)
                at com.hiczp.bilibili.api.BilibiliClient.getToken(BilibiliClient.kt:71)
                at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:83)
                at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:44)
                at com.hiczp.bilibili.api.retrofit.interceptor.CommonParamInterceptor.intercept(CommonParamInterceptor.kt:80)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
                at com.hiczp.bilibili.api.retrofit.interceptor.CommonHeaderInterceptor.intercept(CommonHeaderInterceptor.kt:20)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
                at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
                at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
                ... 3 more

        at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:83)
        at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:44)>
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonParamInterceptor.intercept(CommonParamInterceptor.kt:80)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonHeaderInterceptor.intercept(CommonHeaderInterceptor.kt:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

## 使用环境 (必须)

 - Java 版本:1.8
 - Comet-Bot 版本:Comet-0.6.2-dev-898df54-all

**Comment by StarWishsama** [comment]
`at com.hiczp.bilibili.api.passport.model.LoginResponse.getToken(LoginResponse.kt:60)`

是不是启动显示登录失败了

**Comment by Damonlove** [comment]
登录时通过了滑块验证提示登陆成功

**Comment by StarWishsama** [comment]
尝试最新构建 https://github.com/StarWishsama/Comet-Bot/actions/runs/888057118

**Comment by Damonlove** [comment]
![image](https://user-images.githubusercontent.com/44105629/120067963-db3e4380-c0b0-11eb-9ef7-5aac39366162.png)

21/5/29 19:04:56 WARN/W Comet -> 在搜索B站用户时出现了意外

java.io.IOException: canceled due to java.lang.NullPointerException
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.NullPointerException
                at com.hiczp.bilibili.api.passport.model.LoginResponse.getToken(LoginResponse.kt:60)
                at com.hiczp.bilibili.api.BilibiliClient.getToken(BilibiliClient.kt:71)
                at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:83)
                at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:44)
                at com.hiczp.bilibili.api.retrofit.interceptor.CommonParamInterceptor.intercept(CommonParamInterceptor.kt:80)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
                at com.hiczp.bilibili.api.retrofit.interceptor.CommonHeaderInterceptor.intercept(CommonHeaderInterceptor.kt:20)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
                at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
                at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
                ... 3 more


        at com.hiczp.bilibili.api.passport.model.LoginResponse.getToken(LoginResponse.kt:60)
        at com.hiczp.bilibili.api.BilibiliClient.getToken(BilibiliClient.kt:71)>
        at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:83)
        at com.hiczp.bilibili.api.BilibiliClient$defaultCommonParamArray$1.invoke(BilibiliClient.kt:44)
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonParamInterceptor.intercept(CommonParamInterceptor.kt:80)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonHeaderInterceptor.intercept(CommonHeaderInterceptor.kt:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by StarWishsama** [comment]
首次哔哩哔哩登录状态那一条显示为 true 吗？

**Comment by Damonlove** [comment]
是的
![image](https://user-images.githubusercontent.com/44105629/120073592-907df500-c0cb-11eb-8369-e7ce5f5f8be7.png)

**Comment by StarWishsama** [comment]
暂时先不要用登录，其实搜索 API 不用登录

**Comment by StarWishsama** [comment]
https://github.com/StarWishsama/Comet-Bot/actions/runs/910992083

**Comment by Damonlove** [comment]
好的

**Comment by StarWishsama** [comment]
#90
