### ISSUE TITLE
Bilibili执行验证码验证后Bot无法使用Bilibili功能

### ISSUE THREAD

**Issue by Stardust-minus** [StarWishsama/Nameless-Bot#258]
## 描述 (必须)
执行验证码验证后Bot无法使用Bilibili功能

## 复现步骤 (必须)
在/api/bilibili写入账号密码，启动提示验证码，按步骤输入challenge和balidate后提示成功登陆，但bot的bilibili功能不可用。
再次登录仍提示验证码

## Log / Comet-Bot 的报错
21/6/22 08:39:43 WARN/W CometService -> 极验滑块链接: https://passport.bilibili.com/register/verification.html?success=1&gt=b6e5b7fa*************
需要滑块验证码登录, 请稍后在后台用 /bili retry 进行进一步操作!
需要将获得的 challenge 和 validate 填入, 如果不懂如何获取请查看 Wiki
21/6/22 08:40:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Send: Heartbeat.Alive
21/6/22 08:40:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Recv: Heartbeat.Alive.Response
>bili login 131******06 ********
21/6/22 08:41:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Send: Heartbeat.Alive
21/6/22 08:41:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Recv: Heartbeat.Alive.Response
21/6/22 08:41:39 DEBUG/D(i.g.s.c.a.t.b.FakeClientApi$login$3#invokeSuspend:32) CometService ->

com.hiczp.bilibili.api.retrofit.exception.BilibiliApiException: 验证码错误
        at com.hiczp.bilibili.api.retrofit.interceptor.FailureResponseInterceptor.intercept(FailureResponseInterceptor.kt:47)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.hiczp.bilibili.api.retrofit.interceptor.SortAndSignInterceptor.intercept(SortAndSignInterceptor.kt:60)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonParamInterceptor.intercept(CommonParamInterceptor.kt:68)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.hiczp.bilibili.api.retrofit.interceptor.CommonHeaderInterceptor.intercept(CommonHeaderInterceptor.kt:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

21/6/22 08:41:39 WARN/W CometService -> 极验滑块链接: https://passport.bilibili.com/register/verification.html?success=1&gt*****************8&challenge=7950e*******22364720&ct=1&hash=c5f2c156bc45d199981a2d4e07f8f727
需要滑块验证码登录, 请稍后在后台用 /bili retry 进行进一步操作!
需要将获得的 challenge 和 validate 填入, 如果不懂如何获取请查看 Wiki
21/6/22 08:41:39 INFO/I CometConsole -> /bili login [手机号/邮箱/UID] [密码] 登录哔哩哔哩
/bili retry [challenge] [validate] 通过极验验证码重试登录
21/6/22 08:42:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Send: Heartbeat.Alive
21/6/22 08:42:35 VERBOSE/V CometNet -> MiraiNet (2055170746) Recv: Heartbeat.Alive.Response
>/bili retry a6ca1534c5************93885368e3d d270e75f659af**********61dc13
21/6/22 08:42:47 INFO/I CometService -> challenge = a6ca1534c5271d***********885368e3d, validate = d270e75f6***********599a61dc13
21/6/22 08:43:01 INFO/I CometService -> 成功登录哔哩哔哩账号
21/6/22 08:43:01 INFO/I CometConsole -> /bili login [手机号/邮箱/UID] [密码] 登录哔哩哔哩
/bili retry [challenge] [validate] 通过极验验证码重试登录
21/6/22 08:43:17 VERBOSE/V Comet -> Mirai (2055170746) [杰克姚の小屋(1045814906)] Stardust·星尘 ~喵(2225664821) -> /bili sub
21/6/22 08:43:24 VERBOSE/V Comet -> Mirai (2055170746) [杰克姚の小屋(1045814906)] Stardust·星尘 ~喵(2225664821) -> /bili info 杰克姚
21/6/22 08:43:31 VERBOSE/V CometNet -> MiraiNet (2055170746) Send: MessageSvc.PbSendMsg
21/6/22 08:43:31 VERBOSE/V CometNet -> MiraiNet (2055170746) Recv: MessageSvcPbSendMsg.Response.SUCCESS
21/6/22 08:43:31 VERBOSE/V CometNet -> MiraiNet (2055170746) Send: MessageSvc.PbSendMsg
21/6/22 08:43:31 VERBOSE/V Comet -> Mirai (2055170746) Group(1045814906) <- Comet > 未登录无法使用查询功能, 请在配置中配置B站账号密码
## 使用环境 (必须)
Windows Server 1809（64bit）

 - Java 版本:JDK 11.0.11（orcale）  zip release
 - Comet-Bot 版本:0.6.1 jar release

**Comment by Stardust-minus** [comment]
换用0.6.2 7f2b572 dev构建版本后症状消失。
似乎是目前的stable版本有BUG

**Comment by StarWishsama** [comment]
新版本已不再需要登录哔哩哔哩账号。
