### ISSUE TITLE
Mirai 侧登录失败

### ISSUE THREAD

**Issue by alphagocc** [StarWishsama/Nameless-Bot#268]
## 描述 (必须)

![image](https://user-images.githubusercontent.com/28982331/124473241-a751ee80-ddd1-11eb-9f04-23bf0f3713c9.png)
无法登陆，QQ版本过低
## Log / Comet-Bot 的报错

```
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2908376026), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:247)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

21/7/05 20:42:46 WARN/W CometService -> 登录失败! 返回的失败信息: Error(bot=Bot(2908376026), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)
```
## 使用环境 (必须)

 - OS: Ubuntu 20.04 LTS
 - Java 版本: 11
 - Comet-Bot 版本: 0.6.2

**Comment by StarWishsama** [comment]
请尝试更换登录协议

**Comment by alphagocc** [comment]
~~好，但是我没有找到哪里更换登陆协议，是要重新编译吗~~

找到了

**Comment by alphagocc** [comment]
已尝试所有协议，均无法登陆

**Comment by alphagocc** [comment]
是否考虑是 Mirai 本身的问题

**Comment by StarWishsama** [comment]
如果本地可行的话，可以手动复制一份 device.json

**Comment by alphagocc** [comment]
我来试试

**Comment by StarWishsama** [comment]
尝试 https://github.com/StarWishsama/Comet-Bot/runs/2999993818

Mirai 貌似修改了一些登录相关的功能，已更新到 2.7-M2

**Comment by StarWishsama** [comment]
能登录了吗

**Comment by alphagocc** [comment]
好了，感谢
