### ISSUE TITLE
/music点歌命令报错：拒绝连接

### ISSUE THREAD

**Issue by stars-spark** [StarWishsama/Nameless-Bot#399]
2022-06-21 19:37:17 V/Bot.1038114571: [小灵、怀良辰以孤往(443222943)] 怀良辰以孤往(3560701871) -> /music 孤勇者
2022-06-21 19:37:18 V/Bot.1038114571: Group(443222943) <- 请稍等...
2022-06-21 19:37:18 W/Comet: 22/6/21 19:37:18 WARN/W CometNet -> 执行网络操作失败: https://api.qq.jsososo.com/song/urls?id=003UkWuI0E8U0l

java.net.ConnectException: Failed to connect to api.qq.jsososo.com/47.111.244.251:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.service.RetrofitLogger.intercept(RetrofitInterceptor.kt:30)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.utils.network.NetUtil.executeHttpRequest(NetUtil.kt:129)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.utils.network.NetUtil.executeHttpRequest$default(NetUtil.kt:115)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.utils.network.NetUtil.getPageContent(NetUtil.kt:152)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.utils.network.NetUtil.getPageContent$default(NetUtil.kt:145)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.api.thirdparty.music.ThirdPartyMusicApi.searchQQMusic(ThirdPartyMusicApi.kt:123)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.api.thirdparty.music.ThirdPartyMusicApi.searchQQMusic$default(ThirdPartyMusicApi.kt:108)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.service.command.MusicService.handleQQMusic(MusicService.kt:79)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.service.command.MusicService.handleMusicSearch(MusicService.kt:46)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.commands.chats.MusicCommand.execute(MusicCommand.kt:47)
	at Comet-0.6.7-mirai-console-24c4cd8b.mirai (1).jar//io.github.starwishsama.comet.commands.chats.MusicCommand$execute$1.invokeSuspend(MusicCommand.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 33 more

2022-06-21 19:37:19 E/main: Exception in coroutine <unnamed>
java.lang.IllegalStateException: Send music share failed. result=901114, errorMsg=param_error: music_url
	at net.mamoe.mirai.internal.network.protocol.data.proto.OidbSso$OIDBSSOPkg.checkSuccess(OIDB.kt:969)
	at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:196)
	at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

>

**Comment by StarWishsama** [comment]
对应服务已关闭，需自行搭建

**Comment by stars-spark** [comment]
> 对应服务已关闭，需自行搭建

请问如何搭建？

**Comment by StarWishsama** [comment]
https://github.com/jsososo/QQMusicApi

**Comment by stars-spark** [comment]
> https://github.com/jsososo/QQMusicApi

谢谢
