### ISSUE TITLE
[Bug] 特定情况下无法完成指令运行

### ISSUE THREAD

**Issue by NealLemonade** [StarWishsama/Nameless-Bot#519]
在本机上运行指令基本正常，但换到虚拟机上/多人同时发送指令会出现如下报错
(不止signin，其他指令一样，表现为这条指令出现错误）

报错：
01-19T15:38:27 - W [DefaultDispatcher-worker-2] [ren.natsuyuk1.comet.api.command.CommandManager] >>> 在尝试执行命令 signin 时出现异常 
java.lang.IllegalArgumentException: bound must be greater than origin
	at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:218)
	at java.base/java.util.random.RandomGenerator.nextDouble(RandomGenerator.java:615)
	at ren.natsuyuk1.comet.commands.service.SignInService.calculate(SignInService.kt:166)
	at ren.natsuyuk1.comet.commands.service.SignInService.signIn(SignInService.kt:53)
	at ren.natsuyuk1.comet.commands.service.SignInService.processSignIn(SignInService.kt:48)
	at ren.natsuyuk1.comet.commands.SignInCommand.run(SignInCommand.kt:40)
	at moe.sdl.yac.parsers.Parser.parse(Parser.kt:193)
	at moe.sdl.yac.parsers.Parser.parse(Parser.kt:24)
	at moe.sdl.yac.core.CliktCommand.parse(CliktCommand.kt:241)
	at moe.sdl.yac.core.CliktCommand.parse$default(CliktCommand.kt:239)
	at moe.sdl.yac.core.CliktCommand.main(CliktCommand.kt:256)
	at ren.natsuyuk1.comet.api.command.CommandManager$executeCommand$2.invokeSuspend(CommandManager.kt:176)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by StarWishsama** [comment]
`java.lang.IllegalArgumentException: bound must be greater than origin`

你的签到配置可能有误

**Comment by StarWishsama** [comment]
如果没有问题几天内就关 issue 了

**Comment by NealLemonade** [comment]
> Owner

抱歉抱歉后来发现确实自己有问题就没管了 抱歉！！ 没有问题了
